# Generated by Django 4.1.2 on 2022-10-24 05:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.IntegerField()),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Contacttracers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contacttracers',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nric', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('email', models.TextField(blank=True)),
                ('phone', models.TextField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vaccinationtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'vaccinationtypes',
            },
        ),
        migrations.CreateModel(
            name='Infectionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'db_table': 'infectionhistory',
                'unique_together': {('user', 'recorded_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Closecontacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_timestamp', models.DateTimeField()),
                ('rssi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_user', to='main.users')),
                ('infected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infected_user', to='main.users')),
                ('infectionhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.infectionhistory')),
            ],
            options={
                'db_table': 'closecontacts',
            },
        ),
        migrations.CreateModel(
            name='Vaccinationhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vaccinationtypes')),
            ],
            options={
                'db_table': 'vaccinationhistory',
                'unique_together': {('user', 'vaccination', 'date_taken')},
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('infection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.infectionhistory')),
                ('uploaded_status', models.BooleanField(blank=True, null=True)),
                ('tracer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contacttracers')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Buildingaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_timestamp', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'db_table': 'buildingaccess',
                'unique_together': {('user', 'building', 'access_timestamp')},
            },
        ),
    ]
